services:
  nginx:
    image : nginx
    restart: always
    build:
      context: ./requirements/nginx #Directorio donde se encuentra el Dockerfile
      dockerfile: Dockerfile #Nombre del Dockerfile
    volumes:
      - wordpress_data:/var/wordpress_data
    networks:
      - inception-net
    expose:
      - "9000"
    container_name: nginx-container

  mariadb:
    build:
      context:  ./requirements/mariadb
      dockerfile: Dockerfile

volumes:
  mariadb-data:
    name: DB
    driver: local
    driver_opts:
      type: none
      o: bind # Option 
      device: ~/volumes/database-volume
  wordpress_data:
    name: "wordpress-data"
    driver: local
    driver_opts:
      type: none
      o: bind # Option 
      device: ~/volumes/wordpress-volume


networks:
  inception-net:
    driver: bridge
