services:
  mariadb:
    container_name: mariadb
    restart: always
    build:
      context:  ./requirements/mariadb 
      dockerfile: Dockerfile
    image: mariadb
    env_file: ./.env
    volumes:
      -  mariadb:/var/lib/mysql # Me falta esto!!!!
    networks:
      - inception-net

  wordpress:
    container_name: wordpress
    restart: always
    build:
      context: ./requirements/wordpress 
      dockerfile: Dockerfile
    image: wordpress
    env_file: ./.env
    volumes:
      - wordpress:/var/www/html # Me falta esto!!!!
    depends_on:
      - mariadb
    networks:
      - inception-net

  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - wordpress:/var/wordpress_data
    depends_on:
      - wordpress
    networks:
      - inception-net
    ports:
      - 443:443

#En el host
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind # Option for mounting an existing directory
      device: ~/${LOGIN}/data/wordpress-volume
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind # Option for mounting an existing directory
      device: ~/${LOGIN}/data/mariadb-volume


networks:
  inception-net:
    driver: bridge
