services:
  mariadb:
    container_name: mariadb
    restart: always
    build:
      context:  ./requirements/mariadb 
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD" ,"mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 5
    image: mariadb
    env_file: ./.env
    volumes:
      -  mariadb:/var/lib/mysql
    networks:
      - inception-net

  wordpress:
    container_name: wordpress
    restart: always
    build:
      context: ./requirements/wordpress 
      dockerfile: Dockerfile
    image: wordpress
    env_file: ./.env
    volumes:
      - wordpress:/usr/share/webapps/
    depends_on:
      mariadb:
          condition: service_healthy
          restart: true
    networks:
      - inception-net

  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    env_file: ./.env
    volumes:
      - wordpress:/usr/share/webapps/
    depends_on:
      - wordpress
    networks:
      - inception-net
    ports:
      - 443:443

#En el host
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress-volume
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb-volume


networks:
  inception-net:
    driver: bridge



