CREATE DATABASE IF NOT EXISTS `${DB_NAME}` CHARACTER SET utf8;

CREATE USER IF NOT EXISTS '${MDB_USER}'@'%' IDENTIFIED BY '${MDB_USER_PASSWORD}';
CREATE USER IF NOT EXISTS 'Jesus'@'%' IDENTIFIED BY '${MDB_ROOT_PASSWORD}';

GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO '${MDB_USER}'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'Jesus'@'%';

FLUSH PRIVILEGES;