CREATE DATABASE IF NOT EXIST '${DB_NAME}' CHARACTER SET utf8;

CREATE USER IF NOT EXIST '${MDB_USER}'@'%' IDENTIFIED BY '${MDB_USER_PASSWORD}';
CREATE USER IF NOT EXIST 'Jesus'@'%' IDENTIFIED BY '${MDB_ROOT_PASSWORD}';

GRANT ALL ON '${DB_NAME}'.* TO '${MDB_USER}'@'%';
GRANT ALL ON *.* TO 'Jesus'@'%';